server:
  port: 8080

spring:
  profiles:
    active: h2
  sql:
    init:
      mode: always
  datasource:
    initialization-mode: always

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: assign_id
